add junit rporter to ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -34,8 +34,15 @@ jobs:
           mkdir -p bin
           curl -sSL "$(curl -sSL https://api.github.com/repos/vgteam/vg/releases/latest | grep 'browser_download_url.*vg"' | cut -d ':' -f 2,3 | tr -d '"' | sed 's/^ *//g')" >bin/vg
           chmod +x bin/vg
-      - name: Run tests
-        run: PATH=$PATH:$(pwd)/bin CI=true npm run test
       - name: Test build
         run: npm run build
+      - name: Run tests
+        run: PATH=$PATH:$(pwd)/bin CI=true npm run ci:test
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Jest Test Report      # Name of the check run which will be created
+          path: reports/jest-*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results
 
